[platformio]
build_dir = .pio-build

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
upload_port = COM5
monitor_port = COM5
monitor_speed = 250000
board_build.partitions = min_spiffs.csv
board_build.filesystem = spiffs
